# Для начала указываем исходный образ, он будет использован как основа
FROM php:7.4-fpm

# RUN выполняет идущую за ней команду в контексте нашего образа.
# В данном случае мы установим некоторые зависимости и модули PHP.
# Для установки модулей используем команду docker-php-ext-install.
# На каждый RUN создается новый слой в образе, поэтому рекомендуется объединять команды.
RUN apt-get update && apt-get install -y libcurl4-openssl-dev libmagickwand-dev libzip-dev libonig-dev && pecl install imagick \
        && docker-php-ext-enable imagick \
        && docker-php-ext-install -j$(nproc) iconv mysqli mbstring pdo_mysql zip curl sockets soap xml gd iconv mysqli exif \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg

# Добавим свой php.ini, можем в нем определять свои значения конфига
ADD php.ini /usr/local/etc/php/conf.d/40-custom.ini

# Указываем рабочую директорию для PHP
WORKDIR /usr/local/apache2/htdocs

# Запускаем контейнер
# Из документации: The main purpose of a CMD is to provide defaults for an executing container. These defaults can include an executable,
# or they can omit the executable, in which case you must specify an ENTRYPOINT instruction as well.
CMD ["php-fpm"]